baseURL = 'https://zhung-zhu.net/'
languageCode = 'en-us'
title = 'ZHONG ZHU'
disableKinds = ['taxonomy', 'term']
sectionPagesMenu = 'main'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files